---
- project:
    default-branch: main
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
